---
# task/install_python_docker file for docker
- name: "install_python_docker | Install docker packages"
  ansible.builtin.include_role:
    name: ednz_cloud.utils.manage_apt_packages
  vars:
    manage_apt_packages_list: "{{ install_docker_python_packages_list }}"
