---
# task/prerequisites file for docker
- name: "prerequisites | Create group {{ install_docker_group }}"
  ansible.builtin.group:
    name: "{{ install_docker_group }}"
    state: present

- name: "prerequisites | Create directory {{ install_docker_daemon_dir }}"
  ansible.builtin.file:
    path: "{{ install_docker_daemon_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: "prerequisites | Create directory {{ install_docker_data_dir }}"
  ansible.builtin.file:
    path: "{{ install_docker_data_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0710"

- name: "prerequisites | Install required packages"
  ansible.builtin.include_role:
    name: ednz_cloud.utils.manage_apt_packages
  vars:
    manage_apt_packages_list: "{{ install_docker_system_packages_list }}"
