---
- name: "Set generate-check and apply-check variables"
  ansible.builtin.set_fact:
    _manage_netplan_need_generate: false
    _manage_netplan_need_apply: false

- name: "Import install.yml"
  ansible.builtin.include_tasks: install.yml
  when: manage_netplan_install

- name: "Import remove_existing.yml"
  ansible.builtin.include_tasks: remove_existing.yml
  when: manage_netplan_remove_existing

- name: "Import configure.yml"
  ansible.builtin.include_tasks: configure.yml

- name: "Generate netplan configuration"
  ansible.builtin.command:
    cmd: netplan generate
  changed_when: false
  when: _manage_netplan_need_generate

- name: "Apply netplan configuration"
  ansible.builtin.command:
    cmd: netplan apply
  changed_when: false
  when: _manage_netplan_need_apply
