---
- name: "remove_existing | Fetch existing configurations"
  ansible.builtin.find:
    paths: /etc/netplan
    patterns: "*.yml,*.yaml"
  register: _manage_netplan_configs

- name: "remove_existing | Remove existing configurations"
  ansible.builtin.file:
    path: "{{ item['path'] }}"
    state: absent
  loop: "{{ _manage_netplan_configs['files'] }}"
  when: item['path'] != manage_netplan_config_file
    and manage_netplan_configuration != []
