---
galaxy_info:
  namespace: "ednz_cloud"
  role_name: "manage_pip_packages"
  author: "Bertrand Lanson"
  description: "Package management for python on debian-based distros."
  license: "license (BSD, MIT)"
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - noble
        - jammy
    - name: Debian
      versions:
        - bookworm
        - trixie
  galaxy_tags:
    - "ubuntu"
    - "debian"
    - "python3"
    - "pip"
    - "packages"

dependencies: []
