---
# task/systemd file for dns

# This should never be used but just in case
- name: "systemd | Ensure systemd-resolved is usable"
  when:
    - ansible_facts['services'][dns_systemd_resolved_service]['status'] | default('not-found') != 'enabled' or
      ansible_facts['services'][dns_systemd_resolved_service]['state'] | default('not-found') != 'running'
  block:
    - name: "systemd | Install {{ dns_systemd_resolved_package }}"
      ansible.builtin.apt:
        name: "{{ dns_systemd_resolved_package }}"
        state: present
        update_cache: true
        cache_valid_time: 3600

    - name: "systemd | Start and enable {{ dns_systemd_resolved_service }}"
      ansible.builtin.service:
        name: "{{ dns_systemd_resolved_service }}"
        state: started
        enabled: true

- name: "systemd | Ensure systemd-resolved configuration directory exists"
  ansible.builtin.file:
    path: "{{ dns_systemd_resolved_conf_directory }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: "systemd | Copy systemd-resolved configuration"
  ansible.builtin.template:
    src: "10-dns.conf.j2"
    dest: "{{ dns_systemd_resolved_conf_directory }}/10-dns.conf"
    owner: root
    group: root
    mode: "0644"
  register: _dns_systemd_resolved_conf

- name: "systemd | Get current /etc/resolv.conf state"
  ansible.builtin.stat:
    path: /etc/resolv.conf
  register: _dns_current_etc_resolv_conf

- name: "systemd | Set /etc/resolve.conf file"
  when:
    - not _dns_current_etc_resolv_conf.stat.islnk or
      (_dns_current_etc_resolv_conf.stat.islnk and
      _dns_current_etc_resolv_conf.stat.lnk_source != dns_systemd_resolved_stub_file
      )
  block:
    - name: "systemd | Remove incompatible /etc/reoslv.conf file"
      ansible.builtin.file:
        dest: /etc/resolv.conf
        state: absent
      when: not _dns_current_etc_resolv_conf.stat.islnk

    - name: "systemd | Ensure /etc/resolv.conf is symlink to correct stub file"
      ansible.builtin.file:
        src: "{{ dns_systemd_resolved_stub_file }}"
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: "0777"
        state: link

- name: "systemd | Set reload-check & restart-check variable"
  ansible.builtin.set_fact:
    _dns_systemd_resolved_need_reload: true
  when: _dns_systemd_resolved_conf.changed # noqa: no-handler
