---
# task/prerequisites file for manage_repositories
- name: "prerequisites | Update repositories cache"
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: "prerequisites | Install required packages"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ manage_repositories_required_packages }}"
